/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JAVA_jni_PhysicsEngineJNI */

#ifndef _Included_JAVA_jni_PhysicsEngineJNI
#define _Included_JAVA_jni_PhysicsEngineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    createPhysicsWorld
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JAVA_jni_PhysicsEngineJNI_createPhysicsWorld
  (JNIEnv *, jclass);

/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    deletePhysicsWorld
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JAVA_jni_PhysicsEngineJNI_deletePhysicsWorld
  (JNIEnv *, jclass, jlong);

/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    addObject
 * Signature: (JIDDDDDC[D)V
 */
JNIEXPORT void JNICALL Java_JAVA_jni_PhysicsEngineJNI_addObject
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jchar, jdoubleArray);

/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    handleCollisions
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JAVA_jni_PhysicsEngineJNI_handleCollisions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    configureForces
 * Signature: (JI[D)V
 */
JNIEXPORT void JNICALL Java_JAVA_jni_PhysicsEngineJNI_configureForces
  (JNIEnv *, jclass, jlong, jint, jdoubleArray);

/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    stepSimulation
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_JAVA_jni_PhysicsEngineJNI_stepSimulation
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    displayObjectInfo
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_JAVA_jni_PhysicsEngineJNI_displayObjectInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    getObjectState
 * Signature: (JI)LJAVA/ObjectState;
 */
JNIEXPORT jobject JNICALL Java_JAVA_jni_PhysicsEngineJNI_getObjectState
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     JAVA_jni_PhysicsEngineJNI
 * Method:    updateObjectState
 * Signature: (JIDDDD)V
 */
JNIEXPORT void JNICALL Java_JAVA_jni_PhysicsEngineJNI_updateObjectState
  (JNIEnv *, jclass, jlong, jint, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
